# Generated by Django 3.1 on 2020-12-11 08:29

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frienddetail',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('friendlist', picklefield.fields.PickledObjectField(editable=False)),
                ('friendrequest', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
