# Generated by Django 3.1 on 2020-12-11 14:23

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField()),
                ('article', picklefield.fields.PickledObjectField(editable=False)),
                ('image', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
